[2023-03-23T02:07:34.261+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_sklearn scheduled__2023-03-22T00:00:00+00:00 [queued]>
[2023-03-23T02:07:34.306+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v02.get_sklearn scheduled__2023-03-22T00:00:00+00:00 [queued]>
[2023-03-23T02:07:34.316+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-23T02:07:34.321+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-23T02:07:34.323+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-23T02:07:34.426+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): get_sklearn> on 2023-03-22 00:00:00+00:00
[2023-03-23T02:07:34.433+0000] {standard_task_runner.py:55} INFO - Started process 207 to run task
[2023-03-23T02:07:34.449+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v02', 'get_sklearn', 'scheduled__2023-03-22T00:00:00+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpxm4m1uom']
[2023-03-23T02:07:34.460+0000] {standard_task_runner.py:83} INFO - Job 215: Subtask get_sklearn
[2023-03-23T02:07:34.960+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_with_python_dependencies_v02.get_sklearn scheduled__2023-03-22T00:00:00+00:00 [running]> on host 9783a48d7fca
[2023-03-23T02:07:35.438+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ThinhHuynh
AIRFLOW_CTX_DAG_ID=dag_with_python_dependencies_v02
AIRFLOW_CTX_TASK_ID=get_sklearn
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-22T00:00:00+00:00
[2023-03-23T02:07:35.459+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 14, in get_sklearn
    import sklearn
ModuleNotFoundError: No module named 'sklearn'
[2023-03-23T02:07:35.558+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v02, task_id=get_sklearn, execution_date=20230322T000000, start_date=20230323T020734, end_date=20230323T020735
[2023-03-23T02:07:35.654+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 215 for task get_sklearn (No module named 'sklearn'; 207)
[2023-03-23T02:07:35.710+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-23T02:07:35.824+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
